import type { Metadata } from "next";
import "./globals.css";
import { Jost } from "next/font/google";
import { ColorProvider } from "@/contexts/colorContext";

const jost = Jost({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Impact to Your Life",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <head>
        <link rel="icon" href="/favicon2.png" />
      </head>
      <body className={` ${jost.variable} font-jost antialiased`}>
        <ColorProvider defaultColor="#000000">{children}</ColorProvider>
      </body>
    </html>
  );
}
