import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Jost } from "next/font/google";
import Footer from "@/components/Layout/Footer/footer";
import Banner from "@/components/Layout/Banner/banner";
import { ColorProvider } from "@/contexts/colorContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const jost = Jost({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Impact to Your Life",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <head>
        <link rel="icon" href="/favicon2.png" />
      </head>
      <body
        className={`${inter.variable} ${jost.variable} font-jost antialiased`}
      >
        <Banner />
        <ColorProvider defaultColor="#000000">{children}</ColorProvider>
        <Footer />
      </body>
    </html>
  );
}
