import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Jost } from "next/font/google";
import Footer from "@/components/Layout/Footer/footer";
import Banner from "@/components/Layout/Banner/banner";

const inter = Inter({ subsets: ["latin"] });
const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${jost.className} antialiased`}>
        <Banner />
        {children}
        <Footer />
      </body>
    </html>
  );
}
