import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Jost } from "next/font/google";
import Footer from "@/components/Layout/Footer/footer";
import Banner from "@/components/Layout/Banner/banner";
import { ColorProvider } from "@/contexts/colorContext";

const inter = Inter({ subsets: ["latin"] });
const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={`${inter.className} ${jost.className} antialiased`}>
        <Banner />
        <ColorProvider>{children}</ColorProvider>
        <Footer />
      </body>
    </html>
  );
}
